# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://10.2.250.21/wcr_client/WCRBaseCocoaPods.git'
source 'http://10.2.250.21/wcr_client/WCRCourseWareCocoaPods.git'
source 'http://10.2.250.21/wcr_client/WCRPlayerCocoaPods.git'

inhibit_all_warnings!

target 'WCRCourseWareDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WCRCourseWareDemo
  #pod 'WCRCourseWare', :path => '../'
  pod 'WCRCourseWare'
  pod 'Masonry'

end
